title: Son Dos Clicks!
description: Where everything is 'just two clicks away'
url: "https://roque-rivera.github.io/" # Replace YOUR-USERNAME with your GitHub username
baseurl: "/sondos.click"
# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Default layout for all pages
defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git/
  - .github/
  - README.md

# Add this line to specify the repository
repository: Roque-Rivera/sondos.click
